#!/bin/sh
set -e

# install all packages that "ubuntu-drivers autoinstall" installed into the
# live system. Ubiquity calls this with --package-list /run/ubuntu-drivers.autoinstall

PKGLIST=/run/ubuntu-drivers.autoinstall
[ -e $PKGLIST ] || exit 0

# Copy the kms settings before installing the packages
if [ -e /lib/modprobe.d/nvidia-kms.conf ]; then
    cp /lib/modprobe.d/nvidia-kms.conf /target/lib/modprobe.d/nvidia-kms.conf
fi

for p in `cat $PKGLIST`; do
    apt-install $p
done

